version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dwh_mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MysStrongPWDLucid!2020
    ports:
      - 1433:1433
